[tox]
envlist = py{310,311,312,313,314}, minimum-deps-py{310,311,312,313,314}

[gh-actions]
python =
    3.10: py310, minimum-deps-py310
    3.11: py311, minimum-deps-py311
    3.12: py312, minimum-deps-py312
    3.13: py313, minimum-deps-py313
    3.14: py314, minimum-deps-py314

[testenv]
description = Run the unit tests
deps =
    -r {toxinidir}/requirements.txt
    -r {toxinidir}/requirements-dev.txt
commands =
    pytest {toxinidir}

[testenv:minimum-deps-py{310,311,312,313,314}]
description = Run the unit tests with minimum dependencies
deps =
    -r {toxinidir}/requirements.txt
    graphix-qasm-parser
    pytest
    pytest-mock
commands =
    pytest {toxinidir}
