name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2022", "macos-latest"]
        python: ["3.10", "3.11", "3.12"]

    name: "Python ${{ matrix.python }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install tox
        run: pip install tox tox-gh-actions

      - name: Install the dependencies
        run: pip install -r requirements.txt

      - name: Sample the circuits
        run: python -m veriphix.sampling_circuits.experiments

      - name: Run tox
        run: tox
