name: ruff
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: "requirements-dev.txt"
          args: "check --output-format=github"

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: "requirements-dev.txt"
          args: "format --check"
